travis:
  secure:
    BINSTAR_TOKEN: lAHijpFhcY3IwmkIZ2KWau/UHCsUWP0YKQ06TTU/Pj8PiEQ9CTmsXowqxLEftbW2R07fibr0MJ+8pCOtZkKI2PZt1bRTFzxOFuHeh6JusE7/uPqOAOZY0pyL5Wpfbdcw73bIpp0tfKO1z7gWALCISYR12a8dGNc4e0avfMDl5/UxKrG/A77PRrmcYEVKFG4HLZakqqqAQQ43PvzFKFPUKjN0mKcl3wAwFlr4tyyuty+EIrnL0ctKpDB/MAo99u6DHj5RtynKUZ+Mmv0hgYViNrHxtyUkMuS+osRS/wE1vnQy58bOrWZK77J4AJjSRepbJddx4s8OcUDqFDjoWY5vY6LiTcQE3dUUG226ubc01MiNhEj7Q63o31Kt4jIRT4bDhsKiIvaFcgqmz4Tf/zqBhdSTCFbUld5JP57LwVn5foTSpGmDxyStsDnihzAC66eUFXSY+OGyvqQczIw+Gt0kYew8Yw9YF8mMAN9uF0dpOZ2HNY20fE5IACec7zdCZo3x/hYj1+WddiE34aXTsI4Wp0U3gzF6/WbCsG+QWqLZH6ZYgNeybeAa1hlm0q3scqqwoDEw9e/6iazBygqdaMyhP73hdwoGGhejEyO281RxEWMibEKHWbZPo9YNGUZhW6otXqjVQag4ksm/yOGNG9Y29XpaX2UXjXAJP3AZtUdNEn4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
